excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://fagoner.github.io
title: Una forma de poder comunicarme al mundo
email: farendaway@gmail.com
author: fagoner
description: Mi manera de comunicarme :)
paginate: 3
google_analytics: 
